version: '2'
services:
  keycloak:
    image: docker.io/bitnami/keycloak:12-debian-10
    environment:
      DB_ADDR: postgresql
      DB_DATABASE: kc
      DB_PASSWORD: ''
      DB_PORT: '5432'
      DB_SCHEMA: public
      DB_USER: kc
      DB_VENDOR: POSTGRES
      KEYCLOAK_CREATE_ADMIN_USER: 'true'
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: admin
    ports:
    - 8022:8080
    - 9990:9990
    labels:
      io.rancher.scheduler.affinity:host_label: name=mycic
  postgresql:
    image: docker.io/bitnami/postgresql:11-debian-10
    hostname: postgresql
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      POSTGRESQL_DATABASE: kc
      POSTGRESQL_USERNAME: kc
    volumes:
    - /var/lib/keycloak/postgres-data2:/bitnami/postgresql
    labels:
      io.rancher.scheduler.affinity:host_label: name=mycic


version: '2'
services:
  keycloak:
    scale: 1
    start_on_create: true
  postgresql:
    scale: 1
    start_on_create: true
